import hashlib as hs

def my_hash():
    
    file=".\certificate.pdf"
    BLOCK_SIZE=65536
    
    hashed=hs.sha256() 
    with open(file,'rb') as f: 
        
        fb=f.read(BLOCK_SIZE) 

        while len(fb)>0: 
            hashed.update(fb) 
            fb=f.read(BLOCK_SIZE) 

    dig=hashed.hexdigest()
    
    global digest
    digest=int(dig, 16)

    print("Digest generated by me:",digest)
    return digest


def rec_hash():
    
    with open('Signature.txt') as sg:
        sgn=sg.read()
    
    signature=int(sgn)
    
    with open('Public.txt') as pb:
        p=pb.read()
    
    public=int(p)
    
    with open('Modulo.txt') as md:
        m=md.read()
        
    modulo=int(m)
    
    digCheck=pow(signature,public,modulo)
    
    print("Received digest:",digCheck)
    
    if (digCheck==digest):
        print("Received file is legitimate")
    
    else:
        print("Received file is fake")
    
    return digCheck
    

if __name__=="__main__":
    my_hash()
    rec_hash()